# Generated by Django 2.2.7 on 2019-11-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oslides_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slideshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='oslides_app.Slideshow'),
        ),
    ]
